[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spectre"
version = "0.1.0"
description = "Edge and Graph Analysis Toolkit"
authors = [
    { name = "bohemian-miser" }
]
dependencies = [
    "click"
]

[project.scripts]
spectre = "spectre.cli:cli"
