/-
  GENERATED by `web/sel15-proof/04-emit-lean.ts` from `web/sel15-proof/atlas.json`.
  Do not edit by hand; re-run the emitter instead.

  The ten cluster types of selection `15`, as abstract labelled graphs. A cluster
  is a connected component of the active-adjacency graph: `kinds` gives each
  member tile's kind in node order, and `links` lists the shared dots as
  `(nodeA, seamA, nodeB, seamB)`. Positions are irrelevant here — the strand
  structure of a cluster depends only on this data.

  Provenance: exact `Z[zeta12]` integer arithmetic over all nine substitution
  roots at levels 1..5, plus level 6 for the Delta and Psi roots.
-/
import Sel15.Basic

namespace Sel15

/-- A cluster as an abstract labelled graph. -/
structure Cluster where
  kinds : List Kind
  links : List (Nat × Nat × Nat × Nat)
  deriving Repr

/-- The complete cluster atlas: five of 3 tiles and 3 chords, five of 6 and 9. -/
def atlas : List Cluster := [
  -- C1: Delta, Gamma1, Gamma1, Pi, Pi, Psi
  { kinds := [.psi, .two, .pi, .pi, .two, .two]
    links := [(0, 0, 1, 1), (0, 1, 2, 2), (0, 2, 3, 1), (0, 3, 4, 0), (1, 0, 2, 3), (2, 0, 5, 1), (2, 1, 3, 2), (4, 1, 3, 0), (5, 0, 3, 3)] },
  -- C2: Delta, Gamma1, Pi, Psi, Psi, Sigma
  { kinds := [.two, .psi, .psi, .pi, .two, .two]
    links := [(0, 0, 1, 3), (0, 1, 2, 0), (1, 0, 5, 1), (1, 1, 3, 2), (2, 1, 1, 2), (2, 2, 3, 1), (2, 3, 4, 0), (4, 1, 3, 0), (5, 0, 3, 3)] },
  -- C3: Delta, Gamma1, Xi
  { kinds := [.two, .two, .two]
    links := [(0, 0, 1, 1), (0, 1, 2, 0), (1, 0, 2, 1)] },
  -- C4: Delta, Phi, Xi
  { kinds := [.two, .two, .two]
    links := [(0, 0, 1, 1), (0, 1, 2, 0), (2, 1, 1, 0)] },
  -- C5: Gamma1, Gamma1, Pi, Pi, Psi, Sigma
  { kinds := [.psi, .two, .pi, .pi, .two, .two]
    links := [(0, 0, 1, 1), (0, 1, 2, 2), (0, 2, 3, 1), (0, 3, 4, 0), (1, 0, 2, 3), (2, 0, 5, 1), (2, 1, 3, 2), (4, 1, 3, 0), (5, 0, 3, 3)] },
  -- C6: Gamma1, Lambda, Xi
  { kinds := [.two, .two, .two]
    links := [(0, 0, 1, 1), (0, 1, 2, 0), (1, 0, 2, 1)] },
  -- C7: Gamma1, Pi, Psi, Psi, Sigma, Sigma
  { kinds := [.two, .psi, .psi, .pi, .two, .two]
    links := [(0, 0, 1, 3), (0, 1, 2, 0), (1, 0, 5, 1), (1, 1, 3, 2), (2, 1, 1, 2), (2, 2, 3, 1), (2, 3, 4, 0), (4, 1, 3, 0), (5, 0, 3, 3)] },
  -- C8: Phi, Phi, Phi
  { kinds := [.two, .two, .two]
    links := [(0, 0, 1, 1), (0, 1, 2, 0), (2, 1, 1, 0)] },
  -- C9: Phi, Sigma, Xi
  { kinds := [.two, .two, .two]
    links := [(0, 0, 1, 1), (0, 1, 2, 0), (2, 1, 1, 0)] },
  -- C10: Psi, Psi, Psi, Sigma, Sigma, Sigma
  { kinds := [.two, .psi, .psi, .psi, .two, .two]
    links := [(0, 0, 1, 3), (0, 1, 2, 0), (5, 1, 1, 0), (3, 2, 1, 1), (2, 1, 1, 2), (2, 2, 3, 1), (2, 3, 4, 0), (4, 1, 3, 0), (3, 3, 5, 0)] }
]

end Sel15
