/**
 * Emit the Lean certificate from the exact-arithmetic atlas.
 *
 * `lean/Sel15/Certificate.lean` is GENERATED — never edit it by hand. It carries
 * the ten cluster types of `01-clusters.ts` in the abstract form the Lean
 * development consumes: per cluster, the kind of each tile (two-dot, Pi or Psi)
 * and the list of shared dots as `(nodeA, seamA, nodeB, seamB)`.
 *
 * Run: cd web && npx --yes tsx sel15-proof/04-emit-lean.ts
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { finish, heading, seamsOf, verdict } from './lib15';
import type { TileTypeId } from '../src/core';

const cert = JSON.parse(readFileSync(new URL('./atlas.json', import.meta.url), 'utf8')) as {
  clusters: { id: string; types: TileTypeId[]; links: [number, number, number, number][] }[];
};

const kindOf = (t: TileTypeId): string => (t === 'Pi' ? '.pi' : t === 'Psi' ? '.psi' : '.two');

heading('Emitting lean/Sel15/Certificate.lean');
let ok = true;
for (const c of cert.clusters) {
  // every seam of every tile must appear in exactly one link
  const seen = new Map<string, number>();
  for (const [a, sa, b, sb] of c.links) {
    for (const k of [`${a}.${sa}`, `${b}.${sb}`]) seen.set(k, (seen.get(k) ?? 0) + 1);
  }
  let good = true;
  c.types.forEach((t, v) => {
    for (let s = 0; s < seamsOf(t).length; s++) if (seen.get(`${v}.${s}`) !== 1) good = false;
  });
  ok = ok && good;
  console.log(
    `        ${c.id.padEnd(4)} ${c.types.length} tiles, ${c.links.length} dots` +
      `  kinds=[${c.types.map(kindOf).join(' ')}]  ${good ? '' : 'BAD'}`,
  );
}
verdict(ok, 'every active dot of every cluster tile is used exactly once');

const body = cert.clusters
  .map(
    (c) =>
      `  -- ${c.id}: ${[...c.types].sort().join(', ')}\n` +
      `  { kinds := [${c.types.map(kindOf).join(', ')}]\n` +
      `    links := [${c.links.map(([a, sa, b, sb]) => `(${a}, ${sa}, ${b}, ${sb})`).join(', ')}] }`,
  )
  .join(',\n');

writeFileSync(
  new URL('../../lean/Sel15/Certificate.lean', import.meta.url),
  `/-
  GENERATED by \`web/sel15-proof/04-emit-lean.ts\` from \`web/sel15-proof/atlas.json\`.
  Do not edit by hand; re-run the emitter instead.

  The ten cluster types of selection \`15\`, as abstract labelled graphs. A cluster
  is a connected component of the active-adjacency graph: \`kinds\` gives each
  member tile's kind in node order, and \`links\` lists the shared dots as
  \`(nodeA, seamA, nodeB, seamB)\`. Positions are irrelevant here — the strand
  structure of a cluster depends only on this data.

  Provenance: exact \`Z[zeta12]\` integer arithmetic over all nine substitution
  roots at levels 1..5, plus level 6 for the Delta and Psi roots.
-/
import Sel15.Basic

namespace Sel15

/-- A cluster as an abstract labelled graph. -/
structure Cluster where
  kinds : List Kind
  links : List (Nat × Nat × Nat × Nat)
  deriving Repr

/-- The complete cluster atlas: five of 3 tiles and 3 chords, five of 6 and 9. -/
def atlas : List Cluster := [
${body}
]

end Sel15
`,
);
console.log('        wrote lean/Sel15/Certificate.lean');
finish();
