/**
 * 06 — Emit the data theories for the Isabelle development in ../../isabelle/.
 *
 * Everything the Isabelle proofs compute with comes from here: the substitution
 * tables of 01 (tables-<family>.json), the level-1 direction and label words,
 * the level-1 corner indices in the shared outline, the level-1 dot indicators
 * of a configuration, and the level-1 routing states read from exact geometry
 * (as 03 does). The Isabelle side re-derives everything else and proves the
 * all-levels statements; see isabelle/README.md.
 *
 * Run: cd web && npx --yes tsx fass-theorem/06-isabelle-data.ts hex128 > ../isabelle/FASS_Data_Hex.thy
 *      cd web && npx --yes tsx fass-theorem/06-isabelle-data.ts spectre1278 > ../isabelle/FASS_Data_Spectre.thy
 *      cd web && npx --yes tsx fass-theorem/06-isabelle-data.ts hex128 lean > ../lean/FASS/DataHex.lean
 *      cd web && npx --yes tsx fass-theorem/06-isabelle-data.ts spectre1278 lean > ../lean/FASS/DataSpectre.lean
 * The Lean data is the same, in Lean 4 syntax, for the machine-checked lean/FASS development.
 */
import { readFileSync } from 'node:fs';
import { zAdd, zKey, type TileTypeId } from '../src/core';
import { CONFIGS, buildStrands, trace, zExpand } from '../fass-proof/lib';
import { TYPES, leaves, outlineOf, edgeLabels } from './geom';

const cfgName = process.argv[2] ?? 'hex128';
const format = process.argv[3] ?? 'isabelle';
const cfg = CONFIGS[cfgName];
const J = JSON.parse(readFileSync(`fass-theorem/tables-${cfg.family}.json`, 'utf8'));
const thy = cfg.family === 'hex' ? 'FASS_Data_Hex' : 'FASS_Data_Spectre';
const sel = new Set(cfg.subset);
const hasDot = (label: string): boolean => { const m = /^(-?)(\d+)\.(\d+)[A-Z]$/.exec(label)!; return +m[3] === 0 && sel.has(+m[2]); };

const idx = (T: string): number => TYPES.indexOf(T as TileTypeId);
const ilist = (xs: number[]): string => `[${xs.join(', ')}]`;
const nestedList = (rows: string[]): string => `[${rows.join(',\n   ')}]`;

// level-1 routing states from geometry (03's geoState): pairs of boundary dot indices, in outline order from corner 0
function geoState(T: TileTypeId): [number, number][] {
  const lv = leaves(cfg.family, T, 1); const o = outlineOf(cfg.family, lv); const n = o.loop.length;
  const corners: number[] = J.corners['1'][T];
  const keys: string[] = [];
  for (let j = 0; j < 6; j++) { const a = corners[j], b = corners[(j + 1) % 6]; const len = ((b - a) % n + n) % n; for (let p = 0; p < len; p++) { const i = (a + p) % n; const ow = o.owner[i]; if (hasDot(edgeLabels(cfg.family, lv[ow.leaf].type)[ow.edge])) keys.push(zKey(zAdd(o.coord.get(o.loop[i])!, o.coord.get(o.loop[(i + 1) % n])!))); } }
  const index = new Map(keys.map((k, i) => [k, i] as const));
  const tr = trace(buildStrands(cfg, zExpand(cfg.family, T, 1)));
  if (tr.circuits.length) throw new Error('level-1 circuit');
  const pairs = tr.arcs.map((arc) => { const [a, b] = arc.endpoints.map((k) => index.get(k)!); return (a < b ? [a, b] : [b, a]) as [number, number]; });
  pairs.sort((x, y) => x[0] - y[0]);
  return pairs;
}


if (format === 'lean') {
  const ns = cfg.family === 'hex' ? 'FASS.DataHex' : 'FASS.DataSpectre';
  const L: string[] = [];
  const tup = (xs: (number | string)[]): string => `(${xs.join(', ')})`;
  L.push(`-- Generated by web/fass-theorem/06-isabelle-data.ts ${cfgName} lean; do not edit.`);
  L.push(`import FASS.Core`);
  L.push(`/-! Family ${cfg.family}, configuration ${cfg.id}. Types 0..8 = ${TYPES.join(' ')};`);
  L.push(`  slots 0..7 (9 = empty slot); meta-edges 0..5; directions 0..11. The tables of tables-${cfg.family}.json. -/`);
  L.push(``);
  L.push(`namespace ${ns}`);
  L.push(`open FASS`);
  L.push(``);
  L.push(`def classes : List (List Int) := [${TYPES.map((T) => `[${(J.classes[T] as number[]).join(', ')}]`).join(',\n  ')}]`);
  L.push(``);
  L.push(`def rules : List (List Nat) := [${TYPES.map((T) => `[${(J.rules[T] as string[]).map((c) => (c === 'null' ? 9 : idx(c))).join(', ')}]`).join(',\n  ')}]`);
  L.push(``);
  L.push(`def B : List (List (List (Nat × Nat))) := [${TYPES.map((T) => `[${(J.B[T] as { s: number; e: number }[][]).map((arc) => `[${arc.map(({ s, e }) => tup([s, e])).join(', ')}]`).join(', ')}]`).join(',\n  ')}]`);
  L.push(``);
  L.push(`def G : List (List ((Nat × Nat) × (Nat × Nat))) := [${TYPES.map((T) => `[${(J.G[T] as [{ s: number; e: number }, { s: number; e: number }][]).map(([a, b]) => `(${tup([a.s, a.e])}, ${tup([b.s, b.e])})`).join(', ')}]`).join(',\n  ')}]`);
  L.push(``);
  L.push(`def Q : List (List Int) := [${TYPES.map((T) => `[${(J.quadCorner['2'][T] as (number | null)[]).map((q) => (q === null ? -1 : q)).join(', ')}]`).join(', ')}]`);
  L.push(`def Q1 : List (List Int) := [${TYPES.map((T) => `[${(J.quadCorner['1'][T] as (number | null)[]).map((q) => (q === null ? -1 : q)).join(', ')}]`).join(', ')}]`);
  L.push(``);
  L.push(`def linear : List (Int × Int) := [${(J.linear as { k: number; m: number }[]).map((l) => tup([l.m ? -1 : 1, l.k])).join(', ')}]`);
  L.push(``);
  L.push(`def corners1 : List (List Nat) := [${TYPES.map((T) => `[${(J.corners['1'][T] as number[]).join(', ')}]`).join(', ')}]`);
  L.push(``);
  L.push(`def dir1 : List (List (List Int)) := [${TYPES.map((T) => `[${(J.words['1'][T] as { dir: number[] }[]).map((w) => `[${w.dir.join(', ')}]`).join(', ')}]`).join(',\n  ')}]`);
  L.push(``);
  const labL = (s: string): string => { const m = /^(-?)(\d+)\.(\d+)[A-Z]$/.exec(s)!; return tup([m[1] ? -1 : 1, m[2], m[3]]); };
  L.push(`def lab1 : List (List (List (Int × Nat × Nat))) := [${TYPES.map((T) => `[${(J.words['1'][T] as { lab: string[] }[]).map((w) => `[${w.lab.map(labL).join(', ')}]`).join(', ')}]`).join(',\n  ')}]`);
  L.push(``);
  L.push(`/-- Configuration ${cfg.id}: which leaf edges of the level-1 meta-edges carry a dot. -/`);
  L.push(`def dots1 : List (List (List Bool)) := [${TYPES.map((T) => `[${(J.words['1'][T] as { lab: string[] }[]).map((w) => `[${w.lab.map((l) => (hasDot(l) ? 'true' : 'false')).join(', ')}]`).join(', ')}]`).join(',\n  ')}]`);
  L.push(``);
  L.push(`/-- The level-1 routing states read from exact geometry: boundary dot indices joined by an arc. -/`);
  L.push(`def state1 : List (List (Nat × Nat)) := [${TYPES.map((T) => `[${geoState(T).map(([a, b]) => tup([a, b])).join(', ')}]`).join(',\n  ')}]`);
  L.push(``);
  L.push(`def tables : Tables := { classes := classes, rules := rules, B := B, G := G, Q := Q, Q1 := Q1, linear := linear }`);
  L.push(``);
  L.push(`end ${ns}`);
  console.log(L.join('\n'));
  process.exit(0);
}

const out: string[] = [];
out.push(`(* Generated by web/fass-theorem/06-isabelle-data.ts ${cfgName}; do not edit. *)`);
out.push(`theory ${thy}`);
out.push(`  imports FASS_Core`);
out.push(`begin`);
out.push(``);
out.push(`text \\<open>Family ${cfg.family}, configuration ${cfg.id}. Types are indexed 0..8 in the order`);
out.push(`  ${TYPES.map((t, i) => `${i}=${t}`).join(' ')}. The hexagon classes of the six meta-edges,`);
out.push(`  the substitution rules (child type per slot, 9 = empty), the tables B, G, CT, Q, the slot`);
out.push(`  linear parts, and the level-1 words are those of tables-${cfg.family}.json.\\<close>`);
out.push(``);
out.push(`definition ${thy.toLowerCase()}_classes :: "int list list" where\n  "${thy.toLowerCase()}_classes = ${nestedList(TYPES.map((T) => ilist(J.classes[T])))}"`);
out.push(``);
out.push(`definition ${thy.toLowerCase()}_rules :: "nat list list" where\n  "${thy.toLowerCase()}_rules = ${nestedList(TYPES.map((T) => ilist((J.rules[T] as string[]).map((c) => (c === 'null' ? 9 : idx(c))))))}"`);
out.push(``);
out.push(`definition ${thy.toLowerCase()}_B :: "(nat \\<times> nat) list list list" where\n  "${thy.toLowerCase()}_B = ${nestedList(TYPES.map((T) => `[${(J.B[T] as { s: number; e: number }[][]).map((arc) => `[${arc.map(({ s, e }) => `(${s},${e})`).join(',')}]`).join(', ')}]`))}"`);
out.push(``);
out.push(`definition ${thy.toLowerCase()}_G :: "((nat \\<times> nat) \\<times> (nat \\<times> nat)) list list" where\n  "${thy.toLowerCase()}_G = ${nestedList(TYPES.map((T) => `[${(J.G[T] as [{ s: number; e: number }, { s: number; e: number }][]).map(([a, b]) => `((${a.s},${a.e}),(${b.s},${b.e}))`).join(',')}]`))}"`);
out.push(``);
out.push(`definition ${thy.toLowerCase()}_Q :: "int list list" where\n  "${thy.toLowerCase()}_Q = ${nestedList(TYPES.map((T) => ilist((J.quadCorner['2'][T] as (number | null)[]).map((q) => (q === null ? -1 : q)))))}"`);
out.push(``);
out.push(`definition ${thy.toLowerCase()}_Q1 :: "int list list" where\n  "${thy.toLowerCase()}_Q1 = ${nestedList(TYPES.map((T) => ilist((J.quadCorner['1'][T] as (number | null)[]).map((q) => (q === null ? -1 : q)))))}"`);
out.push(``);
out.push(`definition ${thy.toLowerCase()}_linear :: "(int \\<times> int) list" where\n  "${thy.toLowerCase()}_linear = [${(J.linear as { k: number; m: number }[]).map((l) => `(${l.m ? -1 : 1},${l.k})`).join(', ')}]"`);
out.push(``);
out.push(`definition ${thy.toLowerCase()}_corners1 :: "nat list list" where\n  "${thy.toLowerCase()}_corners1 = ${nestedList(TYPES.map((T) => ilist(J.corners['1'][T])))}"`);
out.push(``);
out.push(`definition ${thy.toLowerCase()}_dir1 :: "int list list list" where\n  "${thy.toLowerCase()}_dir1 = ${nestedList(TYPES.map((T) => `[${(J.words['1'][T] as { dir: number[] }[]).map((w) => ilist(w.dir)).join(', ')}]`))}"`);
out.push(``);
// labels as (sign, major, minor) triples
const lab = (s: string): string => { const m = /^(-?)(\d+)\.(\d+)[A-Z]$/.exec(s)!; return `(${m[1] ? -1 : 1},${m[2]},${m[3]})`; };
out.push(`definition ${thy.toLowerCase()}_lab1 :: "(int \\<times> nat \\<times> nat) list list list" where\n  "${thy.toLowerCase()}_lab1 = ${nestedList(TYPES.map((T) => `[${(J.words['1'][T] as { lab: string[] }[]).map((w) => `[${w.lab.map(lab).join(',')}]`).join(', ')}]`))}"`);
out.push(``);
out.push(`text \\<open>Configuration ${cfg.id}: which leaf edges of the level-1 meta-edges carry a dot, and the`);
out.push(`  level-1 routing states (pairs of boundary dot indices joined by an arc) read from exact geometry.\\<close>`);
out.push(``);
out.push(`definition ${thy.toLowerCase()}_dots1 :: "bool list list list" where\n  "${thy.toLowerCase()}_dots1 = ${nestedList(TYPES.map((T) => `[${(J.words['1'][T] as { lab: string[] }[]).map((w) => `[${w.lab.map((l) => (hasDot(l) ? 'True' : 'False')).join(',')}]`).join(', ')}]`))}"`);
out.push(``);
out.push(`definition ${thy.toLowerCase()}_state1 :: "(nat \\<times> nat) list list" where\n  "${thy.toLowerCase()}_state1 = ${nestedList(TYPES.map((T) => `[${geoState(T).map(([a, b]) => `(${a},${b})`).join(',')}]`))}"`);
out.push(``);
out.push(`definition ${thy.toLowerCase()}_tables :: "tables" where\n  "${thy.toLowerCase()}_tables = \\<lparr> classes = ${thy.toLowerCase()}_classes, rules = ${thy.toLowerCase()}_rules, B = ${thy.toLowerCase()}_B, G = ${thy.toLowerCase()}_G, Q = ${thy.toLowerCase()}_Q, Q1 = ${thy.toLowerCase()}_Q1, linear = ${thy.toLowerCase()}_linear \\<rparr>"`);
out.push(``);
out.push(`end`);
console.log(out.join('\n'));
